[package]
name = "near-social"
version = "0.2.2"
authors = ["FroVolod <frol_off@meta.ua>", "frol <frolvlad@gmail.com>"]
license = "MIT OR Apache-2.0"
edition = "2021"
repository = "https://github.com/FroVolod/near-social"
description = "Command line utility helps to develop widgets for near.social by allowing developers to use standard developer tools like their best code editor and standard tools for source code version control, and then deploy their widgets to SocialDB in one command."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "near-social"
path = "src/main.rs"

[dependencies]
clap = { version = "4.0.18", features = ["derive"] }
inquire = "0.5"
strum = { version = "0.24", features = ["derive"] }
strum_macros = "0.24"

tokio = { version = "1.0", features = [ "rt-multi-thread" ] }
futures = "0.3"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.57"

shell-words = "1.0.0"

color-eyre = "0.6"

similar = { version = "2.2.1", features = ["inline"] }
glob = "0.3.1"
lazy_static = "1.4.0"
linked-hash-map = "0.5.6"

near-crypto = "0.15"
near-primitives = "0.15"
near-jsonrpc-client = "0.4.0"
near-jsonrpc-primitives = "0.15"

interactive-clap = "0.1.0"
interactive-clap-derive = "0.1.0"
console = "0.15.5"

near-cli-rs = { git = "https://github.com/near/near-cli-rs", rev="e156eae64b9044d5f40e34880e863a4539e6291d" }

[target.'cfg(target_os = "macos")'.dependencies]
security-framework = "2.7.0"

[features]
default = ["ledger"]
ledger = ["near-cli-rs/ledger"]

# generated by 'cargo dist init'
[profile.dist]
inherits = "release"
debug = true
split-debuginfo = "packed"
